---
# tasks file for login-center

- name: Check install login-center
  ansible.builtin.stat:
    path: "{{ login_center_path }}"
  register: login_center_path_state

- name: Install login center
  ansible.builtin.include_tasks: login_center_install.yml
  when: not login_center_path_state.stat.exists

- name: Check version login-center
  block:
    - name: get remote emv file
      ansible.builtin.slurp:
        path: "{{ login_center_path }}/.env"
      register: env_file_content

    - name: Decode enf file
      ansible.builtin.set_fact:
        env_file: "{{ env_file_content['content'] | b64decode }}"

    - name: get current version login-center
      ansible.builtin.set_fact:
        login_center_version: "{{ env_file.split('\n')[0].split('=')[1] }}"

    - name: update login-center
      ansible.builtin.include_tasks: login_center_update.yml
      when: version != login_center_version
  when: login_center_path_state.stat.exists

# temp. For test install role
- name: Install login center
  ansible.builtin.include_tasks: login_center_install.yml
