---
# handlers file for lc-docker

- name: Docker stop service
  ansible.builtin.service:
    name: docker
    state: stopped
  register: docker_state

- name: Docker start service
  ansible.builtin.service:
    name: docker
    state: started
